pythonapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from .views import HomeView, home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='homeview'),
    # path('',TemplateView.as_view(template_name='home.html'), name='homeview'),
    path('home/', home, name='home'),
    path('tuition/', include('tuition.urls')),
    path('session/', include('session.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

session/urls.py
from unicodedata import name
from django.urls import path

from .views import change_password, loginuser, logoutuser, ownerprofile, registration, userProfile
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

app_name = "session"
urlpatterns = [
    path('login/', loginuser, name='loginuser'),
    path('logout/', logoutuser, name='logoutuser'),
    path('registration/', registration, name='registration'),
    path('changepassword/', change_password, name='chagnepassword'),
    path('reset/password/', PasswordResetView.as_view(
        template_name='session/resetpassword.html'), name="password_reset"),
    path('reset/password/done', PasswordResetDoneView.as_view(
        template_name='session/resetpassworddone.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='session/password_reset_confirm.html'), name="password_reset_confirm"),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='session/password_reset_complete.html'), name="password_reset_complete"),
    path('userprofile/', userProfile, name='userprofile'),
    path('ownerprofile/', ownerprofile, name='ownerprofile')
]

session/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.
class Profile(models.Model):
    BlOOD_GROUP = (
        ('A+', 'A+'),
        ('B+', 'B+'),
        ('O+', 'O+'),
        ('A-', 'A-'),
        ('B-', 'B-'),
        ('O-', 'O-'),
        ('AB+', 'AB+'),
        ('AB-', 'AB-'),
    )
    GENRE_CHOICES = (
        ('Male', 'MALE'),
        ('Female', 'FEMALE'),
    )
    CATEGORY = (
        ('Student', 'Student'),
        ('Teacher', 'Teacher'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birth_date = models.DateField()
    blood_group = models.CharField(max_length=10, choices=BlOOD_GROUP)
    gender = models.CharField(max_length=50, choices=GENRE_CHOICES)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=11)
    nationality = models.CharField(max_length=30)
    religion = models.CharField(max_length=50)
    biodata = models.TextField()
    profession = models.CharField(max_length=50, choices=CATEGORY)
    image = models.ImageField(default='default.png',
                              upload_to='session/images')

    def __str__(self):
        return f'{self.user.username}Profiles'

    def save(self):
        super().save()
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300 :
            output_size =(300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

session/forms.py
from pyexpat import model
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from session.models import Profile


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email','first_name','last_name' ,'password1', 'password2')

class UserProfileForm(forms.ModelForm):
    birth_date=forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model=Profile
        exclude=('user',)

session/views.py
import email
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from .forms import SignupForm, UserProfileForm
from .models import Profile

# Create your views here.


def loginuser(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('homeview')
            else:
                messages.error(request, 'Invalid username or password')
        else:
            messages.error(request, 'Invalid username or password')
    else:
        form = AuthenticationForm()
    return render(request, 'session/login.html', {'form': form})


def logoutuser(request):
    logout(request)
    messages.success(request, 'Logged out successfully')
    return redirect('homeview')


def registration(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            current_site = get_current_site(request)
            mail_subject = "An Account Created"
            message = render_to_string('session/account.html', {
                'user': user,
                'domain': current_site.domain
            })
            send_mail = form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[send_mail])
            email.send()
            username = form.cleaned_data.get('username')
            messages.success(
                request, 'Account created for please Check usermail ' + username)
            return redirect('session:loginuser')
    else:
        form = SignupForm()
    return render(request, 'session/register.html', {'form': form})


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            update_session_auth_hash(request, form.user)
            messages.success(request, "Password Successfully Change!!")
            return redirect('homeveiw')
    else:
        form = PasswordChangeForm(user=request.user)
    return render(request, 'session/change_pass.html', {'form': form})


def userProfile(request):
    try:
        instance = Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        instance = None
    if request.method == 'POST':
        if instance:
            form = UserProfileForm(
                request.POST, request.FILES, instance=instance)
        else:
            form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            messages.success(request, 'Your Profile Save Successfully!!')
            return redirect('homeview')
    else:
        form = UserProfileForm(instance=instance)

    context = {
        'form': form
    }
    return render(request, 'session/updateprofile.html', context)

def ownerprofile(request):
    user = request.user
    return render(request,'session/userprofile.html',{'user':user})

templates/session/account.html
{% autoescape off %}
Hi {{user.username}}
you have successfully Created account on 
http://{{domain}}

if you think ,not you just ignore you ,thank you 


{% endautoescape %}

templates/session/change_pass.html
{% extends 'index.html' %} {% block body %} {% load crispy_forms_tags%}
<div class="container py-2">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-header">Change Password</div>
        <div class="card-body">
          <form action="" method="POST">
            {% csrf_token %} {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Change Password</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

templates/session/login.html
{% extends 'index.html' %} {% block body %} {% load crispy_forms_tags%}
<div class="container py-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-header">Login Here</div>
        <div class="card-body">
            <form action="" method="POST">
              {% csrf_token %} {{ form|crispy }}
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            <div class="text-center">
              <a href="{% url 'session:password_reset' %}" class="btn btn-success text-center">Forget Password</a>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

templates/session/password_reset_complete.html
{% extends 'index.html' %} {% block body %} {% load crispy_forms_tags%}
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-header">Reset Password</div>
        <div class="card-body">
          <h1>Your Password is successfully changed!!</h1>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

templates/session/password_reset_confirm.html
{% extends 'index.html' %} {% block body %} {% load crispy_forms_tags%}
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-header">Reset Password</div>
        <div class="card-body">
          <form action="" method="POST">
            {% csrf_token %} {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Reset passowr</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

templates/session/register.html
{% extends 'index.html' %} {% block body %} {% load crispy_forms_tags%}
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-header">Sign Up Here</div>
        <div class="card-body">
          <form action="" method="POST">
            {% csrf_token %} {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

templates/session/resetpassword.html
{% extends 'index.html' %} {% block body %} {% load crispy_forms_tags%}
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-header">Reset Password</div>
        <div class="card-body">
          <form action="" method="POST">
            {% csrf_token %} {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

templates/session/resetpassworddone.html
{% extends 'index.html' %} {% block body %} {% load crispy_forms_tags%}
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-header">Reset Password</div>
        <div class="card-body">
          <h1>A link is sent to your email , please Check your email</h1>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

templates/session/updateprofile.html
{% extends 'index.html' %} {% block body %} {% load crispy_forms_tags%}
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-header">Sign Up Here</div>
        <div class="card-body">
          <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %} {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Save Profile</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

templates/session/userprofile.html
{% extends 'index.html' %} {% block body %}
{% load humanize %}
<div class="container py-2">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card">
        <div class="row">
          <div class="col-md-4">
            <img src="{{ user.profile.image.url }}" class="img-fluid" alt="Image" />
          </div>
          <div class="col-md-8">
            <div class="card">
              <div class="card-header">
                <h2 class="text-center">Name:{{user.username}}</h2>
                <br>
            
              </div>
              <div class="card-body">
                   <table class="table ">
                       <tr>
                           <td>Blood Group:</td>
                           <td>{{user.profile.blood_group}}</td>
                       </tr>
                       <tr>
                        <td>Address:</td>
                        <td>{{user.profile.address}}</td>
                    </tr>
                    <tr>
                        <td>Phone:</td>
                        <td>{{user.profile.phone}}</td>
                    </tr>
                    <tr>
                        <td>Gender:</td>
                        <td>{{user.profile.gender}}</td>
                    </tr>
                    <tr>
                        <td>Bio Data:</td>
                        <td>{{user.profile.biodata}}</td>
                    </tr>
                    <tr>
                        <td>Profession:</td>
                        <td>{{user.profile.profession}}</td>
                    </tr>
                    <tr>
                        <td>Religion:</td>
                        <td>{{user.profile.religion}}</td>
                    </tr>
                    <tr>
                        <td>Nationality:</td>
                        <td>{{user.profile.nationality}}</td>
                    </tr>
                   </table>
              </div>
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock body %}